version: 0.0
os: linux
files:
  - source: /
    destination: /tmp
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: infra/scripts/after_install.sh
      timeout: 300
      runas: root
