version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "📦 installing packages..."
      - npm --prefix ./benefit-form i --omit=dev
      - npm i --prefix ./admin-panel --omit=dev
  pre_build:
    commands:
      - echo "⚙️ Testing..."
      - echo "✅ Tests passed successfully."
  build:
    commands:
      - echo "🚧 Starting compiling packages..."
      - npm --prefix ./benefit-form run build
      - npm --prefix ./admin-panel run build
      - echo "✅ Build passed successfully."
  post_build:
    commands:
      - echo "🚚 Performing post-build packing and operations..."
      - echo "✅ Post build successful"

artifacts:
  files:
    - "admin-panel/build/*"
    - "benefit-form/build/*"
    - "backend-app/*"
    - "infra/*"
    - "infra/scripts/*"
    - "appspec.yml"
